### ISSUE TITLE
Trouble with StanR compilation

### ISSUE THREAD

**Issue by nhunt32** [stan-dev/stanc3#1455] opened 2024-10-11 09:02 UTC
> m2 <- stan_model("~/2 Quantitative Hui/Palila 2024 Analysis/2021 Palila analysis/Palila/Palila 2021/r/rStan/log-linear SS regression.stan")
Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
  0
Internal compiler error:
TypeError: not a function
[log-linear SS regression.stan.txt](https://github.com/user-attachments/files/17340319/log-linear.SS.regression.stan.txt)

This should never happen. Please file a bug at https://github.com/stan-dev/stanc3/issues/new
and include this message and the model that caused this issue.

-----------------------------------
OS: Windows 10
R version 4.4.1
Rstan Version  2.35

**Comment by WardBrian** [comment] 2024-10-11 14:56
This looks like a duplicate of #1446 -- pinging @andrjohns

**Closed by WardBrian** 2024-10-11 14:56 UTC
