### ISSUE TITLE
warning message - asked to post

### ISSUE THREAD

**Issue by brophyj** [stan-dev/stanc3#758] opened 2020-12-05 14:59 UTC
An newbie Stan user Mac iOS 11.0.1 when I run basic program
`library(rstan)
schools_dat <- list(J = 8, 
                    y = c(28,  8, -3,  7, -1,  1, 18, 12),
                    sigma = c(15, 10, 16, 11,  9, 11, 10, 18))
fit <- stan(file = '~/Documents/stats/stan/8schools.stan', data = schools_dat)
print(fit)
plot(fit)
pairs(fit, pars = c("mu", "tau", "lp__")) `

It runs but with the following message

Compiling Stan program...
sh: clang++ -mmacosx-version-min=10.13: command not found
error in running commandThe NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
cannot remove file '/var/folders/vz/g1j5pr8n7tg786zcwmv2dx8c0000gp/T//Rtmp0nsffw/file142b35347579b.stan', reason 'No such file or directory'Start sampling
cannot open compressed file '/output.rds', probable reason 'Read-only file system'Error in gzfile(file, mode) : cannot open the connection

Suggestions?

**Comment by rok-cesnovar** [comment] 2020-12-07 07:49
Hi, this is a rstan toolchain issue. See https://github.com/stan-dev/rstan/issues/774
Will close as this is a duplicate of that issue.

**Closed by rok-cesnovar** 2020-12-07 07:49 UTC

**Comment by brophyj** [comment] 2020-12-08 22:54
Thanks for the message. I referred to the earlier issue and updated accordingly.
`R> remotes::install_github("stan-dev/rstan", ref = "develop", subdir = "rstan/rstan")
Skipping install of 'rstan' from a github remote, the SHA1 (dac695b3) has not changed since last install.
  Use `force = TRUE` to force installation`
I also created the Makevars file as suggested
`CXX14FLAGS=-O3 -march=native -mtune=native 
CXX14FLAGS += -arch x86_64 -ftemplate-depth-256`
However i still get an error when I run this program (although the error is much shorter!)
`library(rstan) 
schools_dat <- list(J = 8, y = c(28, 8, -3, 7, -1, 1, 18, 12), sigma = c(15, 10, 16, 11, 9, 11, 10, 18)) 
fit <- stan(file = '~/Documents/stats/stan/8schools.stan', data = schools_dat) `
'config' variable 'CPP' is deprecated
clang -mmacosx-version-min=10.13 -E
error in running command
SAMPLING FOR MODEL '8schools' NOW (CHAIN 1).

**Comment by brophyj** [comment] 2020-12-08 23:36
Thanks for the message. I referred to the earlier issue and updated accordingly.
R> remotes::install_github("stan-dev/rstan", ref = "develop", subdir = "rstan/rstan") Skipping install of 'rstan' from a github remote, the SHA1 (dac695b3) has not changed since last install. Use force = TRUE to force installation

I also created the Makevars file as suggested
CXX14FLAGS=-O3 -march=native -mtune=native
CXX14FLAGS += -arch x86_64 -ftemplate-depth-256

However i still get an error when I run this program (although the error is much shorter!)
library(rstan)
schools_dat <- list(J = 8, y = c(28, 8, -3, 7, -1, 1, 18, 12), sigma = c(15, 10, 16, 11, 9, 11, 10, 18))
fit <- stan(file = '~/Documents/stats/stan/8schools.stan', data = schools_dat)

'config' variable 'CPP' is deprecated
clang -mmacosx-version-min=10.13 -E
error in running command
SAMPLING FOR MODEL '8schools' NOW (CHAIN 1).

Thanks

JB
James (Jay) Brophy MD PhD
Professor of Medicine & Epidemiology (McGill University)
website: www.brophyj.com<http://www.brophyj.com>
twitter: @brophyj<https://twitter.com/brophyj>

On Dec 7, 2020, at 2:49 AM, Rok Češnovar <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi, this is a rstan toolchain issue. See stan-dev/rstan#774<https://github.com/stan-dev/rstan/issues/774>
Will close as this is a duplicate of that issue.
