### ISSUE TITLE
[BUG] Internal Compiler Error

### ISSUE THREAD

**Issue by NiekPennings** [stan-dev/stanc3#1472] opened 2024-12-03 13:53 UTC
I'm not sure about writing this issue, but stan told me to so here we are. 
I got the error when pressing the check button in r studio to check for syntactically correctness.
Stan version: 2.35.0
Error message:
```stan
> rstan:::rstudio_stanc("Topic 4/Exercise_3.stan")
Error in stanc(filename, allow_undefined = TRUE) : 0
Internal compiler error:
TypeError: not a function

This should never happen. Please file a bug at https://github.com/stan-dev/stanc3/issues/new
and include this message and the model that caused this issue.
```

Model:
```stan
data {
  int<lower=0> T; # rows
  int<lower=0> N; # cols
  
  matrix[T, N] x;
  matrix[T, N] y;
}

parameters {
  real alpha;
  real beta;
  
  real mu_alpha;
  real<lower=0> sigma_alpha;
  
  real mu_beta;
  real<lower=0> sigma_beta;
}

model {
  
  
  for(i in 1:T){
    for(j in 1:N){
      y[i, j] ~ poisson(exp(alpha + beta*x[i, j]))
    }
  }
  
  alpha ~ normal(mu_alpha, sigma_alpha);
  beta ~ normal(mu_beta, sigma_beta);
  
  mu_alpha ~ normal(0, 1)
  sigma_alpha ~ gamma(2, 2)
  
  mu_beta ~ normal(0, 1)
  sigma_beta ~ gamma(2, 2)
  
}
```

**Comment by WardBrian** [comment] 2024-12-03 14:18
Hi @NiekPennings -- Thanks for reporting. Unfortunately this looks like a duplicate of #1446, which means we can't fix it on the stanc side. 

Just for data collection, are you using RStan from CRAN, r-universe, or source? Do you have the `V8` package installed?

**Closed** 2024-12-03 14:18 UTC

**Comment by NiekPennings** [comment] 2024-12-03 18:24
> Hi @NiekPennings -- Thanks for reporting. Unfortunately this looks like a duplicate of #1446, which means we can't fix it on the stanc side.
> 
> Just for data collection, are you using RStan from CRAN, r-universe, or source? Do you have the `V8` package installed?

I don't exactly know how to check where I'm using RStan from, but I think from source. I don't have the V8 package installed.
