### ISSUE TITLE
ternary operator faulty in stanc3

### ISSUE THREAD

**Issue by wds15** [stan-dev/stanc3#536] opened 2020-05-15 11:31 UTC
I have a model which uses the ternary if-then-else thing `cond ? true-value : false`, but there seems to be a problem with stanc3 as the same model works as expected with stanc2.

Below is a fully working model if you swap the code in the region marked BUG. In essence this is what should work:

```stan
   for (t in (N0+1):N2)
    {
      /* for Stanc3 only this works:
      int start_idx_rev_serial = SI_CUT-t+2;
      int start_idx_E_casesByAge = t-SI_CUT;
      if(start_idx_rev_serial < 1) {
        start_idx_rev_serial = 1;
      }
      if(start_idx_E_casesByAge < 1) {
        start_idx_E_casesByAge = 1;
      }
      */
      // but this should work as well:
      int start_idx_rev_serial = SI_CUT-t+2 < 1 ? 1 : SI_CUT-t+2;
      int start_idx_E_casesByAge = t-SI_CUT < 1 ? 1 : t-SI_CUT;
      {
        row_vector[A] tmp_row_vector_A = rev_serial_interval[start_idx_rev_serial:SI_CUT] * E_casesByAge[start_idx_E_casesByAge:(t-1)];
        E_casesByAge[t] = impact_intv[1,t] * (tmp_row_vector_A * cntct_weekends_mean_local) +
                          impact_intv[2,t] * (tmp_row_vector_A * cntct_weekdays_mean_local);
      }
    }
```

When I use the above code in stanc3, then the start_idx variables get negative indices assigned and the code stops with

```
Unrecoverable error evaluating the log probability at the initial value.
Exception: Exception: Exception: matrix[multi] indexing: accessing element out of range. index -40 out of range; expecting index to be between 1 and 90 (in '../covid19model-mm/run/base_age_google_mobility_200427-v4-rs-cmdstan-buggy.stan', line 113, column 8 to column 135) (in '../covid19model-mm/run/base_age_google_mobility_200427-v4-rs-cmdstan-buggy.stan', line 113, column 8 to column 135) (in '../covid19model-mm/run/base_age_google_mobility_200427-v4-rs-cmdstan-buggy.stan', line 113, column 8 to column 135)
Exception: Exception: Exception: matrix[multi] indexing: accessing element out of range. index -40 out of range; expecting index to be between 1 and 90 (in '../covid19model-mm/run/base_age_google_mobility_200427-v4-rs-cmdstan-buggy.stan', line 113, column 8 to column 135) (in '../covid19model-mm/run/base_age_google_mobility_200427-v4-rs-cmdstan-buggy.stan', line 113, column 8 to column 135) (in '../covid19model-mm/run/base_age_google_mobility_200427-v4-rs-cmdstan-buggy.stan', line 113, column 8 to column 135)
```

Thus, the ternary if is somehow ignored. This used to work with stanc2 just fine.

Codes and data:

[base_age_google_mobility_200427-v4-rs-cmdstan-buggy_stan.txt](https://github.com/stan-dev/stanc3/files/4634062/base_age_google_mobility_200427-v4-rs-cmdstan-buggy_stan.txt)

[base_age_google_mobility_200427-v4-rs-cmdstan_data_R.txt](https://github.com/stan-dev/stanc3/files/4634063/base_age_google_mobility_200427-v4-rs-cmdstan_data_R.txt)

**Comment by bob-carpenter** [comment] 2020-05-16 18:38
Is there a simpler example that fails?  I can't find a problem with the ternary operators themselves in terms of how they bind or return.  These produce the right answer:

```
  int a = 1 - 5 + 0 < 1 ? 1 : 1 - 5 + 2;
  print(a);
  int b = 10 - 5 < 0 ? 10 : 20;
  print(b);
```

**Comment by wds15** [comment] 2020-05-16 19:44
Sorry, I don’t have a shorter example, but this one is reproducible. I also looked at the c++ code which just looks fine to my eyes... I think by now its not a stupid thing in my side (at least for now), which is why we should follow up on this.

**Comment by rybern** [comment] 2020-05-18 18:59
I played around with this a bit. I was able to reproduce, and reducing the code to this:
```
      int start_idx_E_casesByAge;
      if (0) {
        // works
        int z = (t-SI_CUT);
        start_idx_E_casesByAge = z < 1 ? 1 : (t-SI_CUT);
      } else {
        // fails
        start_idx_E_casesByAge = (t-SI_CUT) < 1 ? 1 : (t-SI_CUT);
      }

      {
        row_vector[A] tmp_row_vector_A = rev_serial_interval[start_idx_rev_serial:SI_CUT] * E_casesByAge[start_idx_E_casesByAge:(t-1)];
        E_casesByAge[t] = impact_intv[1,t] * (tmp_row_vector_A * cntct_weekends_mean_local) +
                          impact_intv[2,t] * (tmp_row_vector_A * cntct_weekdays_mean_local);
      }
```
So the two branches of the if statement must not be doing to the same thing. Here's the C++:
```
      int start_idx_E_casesByAge;
      start_idx_E_casesByAge = std::numeric_limits<int>::min();
      
      current_statement__ = 95;
      if (0) {
        int z;
        z = std::numeric_limits<int>::min();
        
        current_statement__ = 92;
        z = (t - SI_CUT);
        current_statement__ = 93;
        start_idx_E_casesByAge = (logical_lt(z, 1) ? 1 : (t - SI_CUT));
      } else {
        current_statement__ = 90;
        start_idx_E_casesByAge = (logical_lt((t - SI_CUT), 1) ? 1 :
                                    (t - SI_CUT));
      }
```

I don't know why those branches would be different, so I'm leaving this to folks more familiar with the C++ side. I did notice that this program uses reduce_sum, I wonder if that has anything to do with it.

**Comment by bob-carpenter** [comment] 2020-05-18 19:11
@rybern Thanks for making this simpler and showing the generated code.

I don't see any way the results could be different in those two blocks of code.  Everything is an `int` in those expressions.  They'll generate different amounts of work, so it could be a race condition from `reduce_sum`.  

@wds15 --- is there a way to run this in a single thread to test if that's the problem?

**Comment by wds15** [comment] 2020-05-18 19:14
sure, will do single thread tomorrow and let you know.

**Comment by nhuurre** [comment] 2020-05-18 19:17
Oh wow, that is subtle. The loop variable `t` in the loop `for (t in (N0+1):N2)` is not an `int`, it's `size_t` which like an _unsigned_ long int. I bet what's happening is that subtracting an int still gives a `size_t` so it just rolls around and will never be less than 0 but assigning to a local `int` variable coerces it to the correct value.

**Comment by rok-cesnovar** [comment] 2020-05-18 19:32
```stan
int start_idx_E_casesByAge1 = t-SI_CUT;
if(start_idx_E_casesByAge1 < 1) {
   start_idx_E_casesByAge1 = 1;
}      
int start_idx_E_casesByAge = t-SI_CUT < 1 ? 1 : t-SI_CUT;
print(start_idx_E_casesByAge1);
print(start_idx_E_casesByAge);
```
prints
1
-40

**Comment by rok-cesnovar** [comment] 2020-05-18 19:34
And print(t-SI_CUT);
prints 18446744073709551576

So yeah, what @nhuurre said.

**Comment by wds15** [comment] 2020-05-18 19:54
Whow...sounds like we need a fix here... very subtle.

**Comment by bob-carpenter** [comment] 2020-05-18 19:55
Nice debugging!  We definitely shouldn't be using `size_t` for `int` values in Stan or for loop indexes.

**Comment by rybern** [comment] 2020-05-18 19:59
I'll go ahead and fix that

**Comment by rybern** [comment] 2020-05-18 20:08
PR does indeed fix the test case

**Comment by rok-cesnovar** [comment] 2020-05-18 20:23
Thanks, I can review tomorrow.

This subtle bug reminds me of the time we had a cmdstan test failing out of nowhere because the timediff to 1.1.1970 overflowed the int it was stored in. Good times, good times.

**Comment by wds15** [comment] 2020-05-18 20:49
I really hesitated to report this bug as I was almost sure that the error is on my side and I got the logic wrong. Glad we got this bug down. Thanks for everyone.

**Closed** 2020-05-19 10:26 UTC
Labels: bug
