### ISSUE TITLE
Can't compute corr_matrix in GQ local env

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/stanc3#811] opened 2021-02-09 17:01 UTC
#### Description:
This works fine:
```stan
generated quantities{
  corr_matrix[num_coef] cor = multiply_lower_tri_self_transpose(chol_corr) ;
}
```
But this:
```stan
generated quantities{
  {
    corr_matrix[num_coef] cor = multiply_lower_tri_self_transpose(chol_corr) ;
  }
}
```
yields the error:
```
Syntax error in '/tmp/RtmpBXFNN9/model-516a25e0bcc0.stan', line 84, column 2 to column 13, parsing error:
   -------------------------------------------------
    82:  generated quantities{
    83:   {
    84:     corr_matrix[num_coef] cor = multiply_lower_tri_self_transpose(chol_corr) ;
           ^
    85:   }
    86:  }
   -------------------------------------------------

Ill-formed phrase. "{" should be followed by a statement, variable declaration or expression.
```

#### Additional Information:
Why do I want to compute a correlation matrix in a local environment? I have an enormous correlation matrix to compute, and it's causing storage issues, so I thought I'd compute the full thing in the local environment then save just the upper-tri via:

```stan
generated quantities{
  vector[num_cors] cor_vec ;
  {
    corr_matrix[num_coef] cor = multiply_lower_tri_self_transpose(chol_corr) ;
    int k = 0 ;
    for(i in 1:(num_coef-1)){
      for(j in (i+1):num_coef){
        k += 1 ;
        cor_vec[k] = cor[i,j] ;
      }
    }
  }
}
```

#### Current Version:
v2.26.0 (via cmdstanr v0.3.0.9000)

**Comment by rok-cesnovar** [comment] 2021-02-09 19:00
Thanks for the report Mike. 

I transferred this to stanc3 as that is where it should be resolved.

**Comment by adamhaber** [comment] 2021-07-11 06:35
@rok-cesnovar I'd be happy to tackle this if you can point me in the right direction (`parser.mly`?). Haven't worked with the parser yet and would be happy to learn.

**Comment by WardBrian** [comment] 2022-05-16 21:26
This is intended behavior, see: https://mc-stan.org/docs/2_29/reference-manual/overview-of-data-types.html#constrained-data-types, emphasis mine
> Declarations of variables _other than local variables_ may be provided with constraints.

The solution posted above where the non-constrained type is used is correct

**Closed by WardBrian** 2022-05-16 21:26 UTC
