### ISSUE TITLE
Expose jacobian function

### ISSUE THREAD

**Issue by spinkney** [stan-dev/stanc3#1172] opened 2022-04-19 10:35 UTC
For some applications like object tracking it becomes tedious to write the jacobian to use within a Stan program. See https://discourse.mc-stan.org/t/jacobian-gradient-function/5614. 

The function exists in stan-math, can we expose it?

**Comment by WardBrian** [comment] 2022-04-20 13:34
Is this function itself differentiable?

**Comment by bob-carpenter** [comment] 2022-04-20 15:34
@spinkney:  This isn't specified as an issue.   There's a pointer to the forums, but that only says

> I am trying to implement Generalized Fiducial Inference into STAN. I was wondering if there already exists a function to calculate the Jacobian.

and doesn't provide a concrete function.  Can you point to the definition in the math library and say what the signature is that's being proposed for the language?  Otherwise, please close this issue until there's enough clarity for someone to implement.  Thanks.

**Comment by bob-carpenter** [comment] 2022-04-20 15:51
Maybe I'm being dense here, but I don't understand which function you're proposing to add to Stan.  The [pointer](https://github.com/stan-dev/stanc3/issues/1172#issuecomment-1104086520) is to a generic Jacobian functor, not anything to do with "generalized fiducial inference" as the link said.  Was the intention to try to expose a Jacobian function, not anything to do with fiducial inference?  Please help me out with the **signature** of the function you want to expose in Stan.

To answer @WardBrian's question, no the implementation of Jacobian in the link is not differentiable---it's hard-coded for `double` arguments.  To differentiate a Jacobian requires second-order autodiff.  To do that, you'd need the forward-mode implementation here:  https://github.com/stan-dev/math/blob/develop/stan/math/fwd/functor/jacobian.hpp

But second-order autodiff isn't supported for the ODE solvers and other implicit functions, so we can't add this to Stan in any generality.

**Comment by spinkney** [comment] 2022-04-20 15:55
I don't know _exactly_ how this would be but something that would mimic the `jacobian` function in R's `numDeriv`. This would take in a function, the vector with which to take the gradient of, and optional other parameters/data like in other Stan functors. It would return a square matrix. 

A recent question about implementing extended kalman filters got me thinking about this. You can see an example of using the jacobian function in R with an extended Kalman filter written out at https://www.magesblog.com/post/2015-01-13-extended-kalman-filter-example-in-r/.

**Comment by bob-carpenter** [comment] 2022-04-20 20:17
@spinkney:   Are you thinking something like this:

```stan
matrix jacobian(F f, vector theta)
```

where `f` has signature `vector f(vector)` and the Jacobian is the derivative of f(theta) w.r.t. theta?

The R version in `numderiv` is much more complicated and allows passing extra args to`f`.  So what they do is more like this:

```stan
matrix jacobian_gen(F f, vector theta, T1 x1, ..., TN xN);
```

where `f` has signature `vector f(vector, T1, ..., TN)` and we return the derivative of `f(theta, x1, ..., xN)` w.r.t. `theta`.  I would much rather stick to the simpler form and replace any potential use of `jacobian_gen(F, theta, x1, ..., xN)` with `jacobian(y.F(y, x1, ..., xN), theta)` . That also lets us be flexible about which argument of `f` we want to differentiate w.r.t..  Picking which argument to differentiate is presumably done with named arguments in `numeric`, but [their doc](https://cran.r-project.org/web/packages/numDeriv/numDeriv.pdf) doesn't actually specify how those extra args are plugged in either the function doc or in an example.

The problem is that we can't implement this function in Stan for the whole language using autodiff because it requires second order derivatives, and those aren't defined for the whole language.   We could do numerical derivatives like the `numDeriv` package in R, but those are very unstable for values and I have no idea how much less stable they'd be (if any) for derivatives.

**Comment by WardBrian** [comment] 2022-04-21 13:42
The fact that the language doesn't perform second order autodiff means I think we can't implement this safely.

**Closed by WardBrian** 2022-04-21 13:42 UTC
Labels: feature

**Comment by bob-carpenter** [comment] 2022-04-21 19:25
> What is the issue with having a function explicitly call Stan's AD to get the derivative and then treat that derivative as a parameter which gets passed to the AD under the hood like any other parameter?

Conceptually, nothing.  In practice, it involves second-order derivatives, which Stan hasn't implemented for every function in the language.  Specifically, when we compute derivatives with reverse mode, we get `double` values, but we need `var` types as input for autodiff.   So we have to compute the derivatives using `fvar<var>` to get second-order autodiff.  

I suggest if this isn't clear that you just try to do what you're suggesting using our autodiff functions in C++ to see where the problem is.
