### ISSUE TITLE
Assignment to vector of different size currently allowed

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/stanc3#523] opened 2020-04-21 17:46 UTC
Here is a test model:

```stan
parameters {
  real a;
}

model {
  vector[3] l1;
  vector[2] l2;
  l1 = rep_vector(1, 2);
  l2 = rep_vector(1, 3);
  print("Length 3: ", l1);
  print("Length 2: ", l2);
  
  a ~ normal(0, 1);
}
```

It produces output:
```
Chain 1 Length 3: [1,1] 
Chain 1 Length 2: [1,1,1]
```

It should print errors like (this is from rstan 2.19.3):
```
SAMPLING FOR MODEL 'm3' NOW (CHAIN 1).
Chain 1: Unrecoverable error evaluating the log probability at the initial value.
Chain 1: Exception: assign: Rows of left-hand-side (3) and rows of right-hand-side (2) must match in size  (in 'model57e03fe8a5ab_m3' at line 8)
```

I made this in issue in stanc3 because it looks like the tests for this are in Math: https://github.com/stan-dev/math/blob/develop/test/unit/math/prim/fun/assign_test.cpp#L54

Edit: This came from: https://discourse.mc-stan.org/t/speeding-up-and-reducing-divergences-for-multivariate-hiearchical-stochastic-factor-model/14366

**Comment by bbbales2** [comment] 2020-04-21 17:51
Pinging the compiler crew, @rok-cesnovar @rybern @nhuurre. Could one of you investigate if this is a stanc3 issue? I don't think it's a math issue. It might be a stan issue.

**Comment by rok-cesnovar** [comment] 2020-04-21 18:09
Well it's kind of both, but the issue is in Stan.

cmdstan develop with stanc2 outputs something similar:

stanc2 assignment:
```cpp
current_statement_begin__ = 8;
stan::math::assign(l1, rep_vector(1, 2));
current_statement_begin__ = 9;
stan::math::assign(l2, rep_vector(1, 3));
```
As you can see this uses the stan math assign from https://github.com/stan-dev/math/blob/develop/stan/math/prim/fun/assign.hpp

In stanc3 its:

```cpp
current_statement__ = 4;
assign(l1, nil_index_list(), rep_vector(1, 2),
          "assigning variable l1");
current_statement__ = 5;
assign(l2, nil_index_list(), rep_vector(1, 3),
          "assigning variable l2");
```
Which in itself is fine. This assign is from the Stan repo: https://github.com/stan-dev/stan/blob/develop/src/stan/model/indexing/lvalue.hpp

And while the stan::math::assign has some checks (not all), Stan repo assign has no checks.

The questions that arise are:
- why do we have two sets of assigns? There might be a reason, I legit don't know.
- should stan::assign have checks?

**Comment by bbbales2** [comment] 2020-04-21 18:14
Ooo, I guess the second is for adding fancy indices. So if I do:

```
l1[1:3] = rep_vector(1.0, 2);
l2[1:2] = rep_vector(1.0, 3);
```

I get the expected errors:
```
Chain 1 Exception: vector[multi] assign sizes: lhs (3) and assigning variable l1 (2) must match in size (in '/tmp/RtmpP94BuT/model-57e06a438d52.stan', line 8, column 2 to column 31)
```

**Comment by rok-cesnovar** [comment] 2020-04-21 18:17
Yep.
This one https://github.com/stan-dev/stan/blob/develop/src/stan/model/indexing/lvalue.hpp#L31 needs a check?

The rest have them (those that need them).

**Comment by bbbales2** [comment] 2020-04-21 18:24
This just feels like the assumptions are different. Like this also doesn't have an assign: https://github.com/stan-dev/stan/blob/develop/src/stan/model/indexing/lvalue.hpp#L47

**Comment by bbbales2** [comment] 2020-04-21 18:29
Makes me think the simpler fix is to code-gen like the old compiler:

```
stan::math::assign(l1, rep_vector(1, 2))
```

What's weird is that the person who found this is using the old compiler (Stan 2.19 and 2.18).

**Comment by rok-cesnovar** [comment] 2020-04-21 18:31
> Like this also doesn't have an assign: https://github.com/stan-dev/stan/blob/develop/src/stan/model/indexing/lvalue.hpp#L47

Yes, but this one resizes the destination, so no check is needed.

> Makes me think the simpler fix is to code-gen like the old compiler:

But then these don't work:
```
l1[1:3] = rep_vector(1.0, 2);
l2[1:2] = rep_vector(1.0, 3);
```

I think adding a check is simpler.

**Comment by bbbales2** [comment] 2020-04-21 18:36
Nono, assignment with indexing should go to the Stan assigns. Assignments without should go to stan::math::assign. That's what I mean.

> Yes, but this one resizes the destination, so no check is needed.

Oh, then it seems like the intent is for these to resize the thing on the left to the thing on the right, in which case no check is correct.

**Comment by rok-cesnovar** [comment] 2020-04-21 18:41
> Oh, then it seems like the intent is for these to resize the thing on the left to the thing on the right, in which case no check is correct.

Seems so. 

But that does seem dangerous to me. Does this have an actual use case? 
Is this behavior considered expected? 

Some functions having checks and others not seems more like these were missed.

**Comment by bbbales2** [comment] 2020-04-21 18:46
> Some functions having checks and others not seems more like these were missed.

True. Is this a two step thing then?

Quick fix to do stan::math::assign and then do the full investigation later?

@bob-carpenter might know the history here.

**Comment by bbbales2** [comment] 2020-04-21 19:17
Oh so the trick to reproducing this in old Stan is doing arrays:

```stan
parameters {
  real a;
}

model {
  vector[3] l1[1];
  vector[2] l2[1];
  l1[1] = rep_vector(1.0, 2);
  l2[1] = rep_vector(1.0, 3);
  print("Length 3: ", l1);
  print("Length 2: ", l2);
  
  a ~ normal(0, 1);
}
```

I vaguely remember there might be some sort of bug here that got used as a hidden feature.

**Comment by rok-cesnovar** [comment] 2020-04-21 20:35
Is this an urgent fix for the release? If so I can make a fix tomorrow. But would like to hear the thoughts of @bob-carpenter before that.

**Comment by bob-carpenter** [comment] 2020-04-21 23:09
> I vaguely remember there might be some sort of bug here that got used as a hidden feature.

Bingo!  This is a longstanding bug where we didn't check sizes during assignment.  The situation now is complicated becuase @bgoodri is using it in various places in RStan for raggedness.  

Eventually we'll have ragged arrays, which will solve this properly.  We'll also have unsized local variables.  But neither of those things exist now.

**Comment by bgoodri** [comment] 2020-04-21 23:22
I don't think I am using that.

**Comment by bbbales2** [comment] 2020-04-22 01:08
@bob-carpenter Is this true for just plain vector variables (that aren't arrays of vectors)? Like would you have expected this to error?

```
vector[3] l1;
vector[2] l2;
l1 = rep_vector(1, 2);
l2 = rep_vector(1, 3);
```

@rok-cesnovar I guess I'm not super concerned about this now that I see what's happening. So I guess this doesn't need to delay release.

**Comment by bob-carpenter** [comment] 2020-04-22 15:01
Yes, my intention all along was to have variables be declared with sizes that never change.  With that spec, the assignment to `l1` should throw an exception at runtime.

The only exception is function arguments, which are unsized.  And in the future, I'd like to allow unsized local variables, like this:

```
vector l1;  // size 0 now
l1 = rep_vector(1, 2);  // now size 2
l1 = rep_vector(1, 5);  // now size 3
```

**Comment by rok-cesnovar** [comment] 2020-12-21 08:48
More reports for this: https://github.com/stan-dev/stanc3/issues/774 and https://github.com/stan-dev/cmdstan/issues/963

**Comment by rok-cesnovar** [comment] 2021-03-10 17:56
The fix for this issue will have to be done in the Stan repo actually, removing stuff like this resize: https://github.com/stan-dev/stan/blob/develop/src/stan/model/indexing/lvalue.hpp#L870

**Comment by SteveBronder** [comment] 2021-10-19 23:04
If Ben's not using this then I'm very pro-fixing this. imo I think what we can do in the compiler is for something like 

```stanc
array[2, 3] x = a_cool_function(y);
```

We could generate the assign like 

```cpp
assign(x, stan::validate_assign_size(a_cool_function(y), "x", 2, 3), ...);
```

where `validate_assign_size()` takes in the rhs as the first argument along with the name and known dimensions. We might have to be a bit careful with slice assignments but that seems very feasible.

**Comment by WardBrian** [comment] 2022-01-21 18:45
I think this is better off living in https://github.com/stan-dev/stan/issues/3084

**Closed by WardBrian** 2022-01-21 18:45 UTC
Labels: bug
