### ISSUE TITLE
Write code for efficiently updating locations for runtime error messages

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#169] opened 2019-06-10 17:51 UTC
The idea could be to use a `std::vector` of strings to store locations which gets assigned once at the start of the program, after which we only need to continually update the index (an integer) to pick out the right error location.

The easiest thing to do is probably to transform the MIR before code-gen:
traverse the MIR once to accumulate a Map of type `(int, location_span) Map.Poly.t` and to replace each metadata location_span with the appropriate number.

Then, the constructed Map can be used to code-gen the std::vector of strings, by using string_of_location_span. And the metadata integer can be used to generate the index.

**Comment by seantalts** [comment] 2019-06-10 18:23
I made one for this already :P #166 Sorry, would have been happy to let you make them!

**Comment by bob-carpenter** [comment] 2019-06-10 20:46
> On Jun 10, 2019, at 1:51 PM, Matthijs Vákár <notifications@github.com> wrote:
> 
> The idea could be to use a std::vector of strings to store locations which gets assigned once at the start of the program, after which we only need to continually update the index (an integer) to pick out the right error location.

We currently maintain a simple index like this, but it's into the full program after includes have been unfolded.  There's then a function that converts that final line number into an include path.

**Comment by VMatthijs** [comment] 2019-06-11 11:19
Whoops. Didn't see your issue, @seantalts . Sorry about that!

**Comment by seantalts** [comment] 2019-06-12 13:52
Closing as duplicate of #166

**Closed by seantalts** 2019-06-12 13:52 UTC
Labels: bug
