### ISSUE TITLE
javascript parser chokes on #-style comments

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stanc3#741] opened 2020-11-15 23:26 UTC
Doing

```{r}
  stanc_ctx <- V8::v8(typed_arrays = FALSE)
  stanc_ctx$source("https://github.com/stan-dev/stanc3/releases/download/nightly/stanc.js")
  stopifnot(stanc_ctx$validate("stanc"))
  stanc_ctx$call("stanc", "comment", "data { int N; # this is an integer }")
```
fails with a weird error message

> Error in context_eval(join(src), private$context, serialize) : 
  0,248,Failure,-3,

whereas it is legal but deprecated with the OCaml parser, which shows

> Warning: deprecated language construct used in '/tmp/test.stan', line 2, column 9:
     1:  data {
     2:    int N; # this is an integer
                  ^
     3:  }
Comments beginning with # are deprecated. Please use // in place of # for line comments.

**Comment by rok-cesnovar** [comment] 2020-11-16 07:56
Technically this is a problem with the R V8 package and how they handle stderr. From what I gather, any writing to stderr will cause this error. Currently we return all syntax/semantic error in the return object (.errors). Any warnings are however still printed in stderr. 

This is not problematic if you run stancjs outside of the V8 R package (like for example in the V8 with node which is what we use for tests) which is why I am saying this is a stanc.js in R V8 thing. We should find a way to work around this on our end not upstream.

You will get the same error if you run stanc with `warn-pedantic` for
```stan
parameters {
	real y;
	real k;
}
model {
    y ~ normal(0,10000);
}
```

or 
```stan
transformed data { 
    real tt;
    tt = tt + 2;
}
```
with `warn-uninitialized`. 

Both are examples in our tests: https://github.com/stan-dev/stanc3/blob/master/test/stancjs/pedantic.js

There may be a way of ignoring this in RV8, but I havent found it. If there is not we need to either: 
- write to stdout not stderr
- fix to return warnings as part of the return object not printed (this is the longterm plan anyways)

**Comment by rok-cesnovar** [comment] 2020-11-16 12:07
You get a similar error if you run

```
> ctx$call("console.error", "something")
Error in context_eval(join(src), private$context, serialize) : something
```

which is a valid Javascript call to print to stderr.

**Comment by bgoodri** [comment] 2020-11-16 16:55
> fix to return warnings as part of the return object not printed (this is the longterm plan anyways)

I would think we would have to go this route. Compiled code isn't supposed to be writing to stdout or stderr according to `#16 ` at

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Checking-packages

and I guess that would apply to V8 as well.

**Comment by rok-cesnovar** [comment] 2020-11-16 19:07
Ok, got it. Will open a PR once https://github.com/stan-dev/stanc3/pull/726 is merged, which is close to happening. That PR refactors the deprecation warnings and then we just return all warnings instead of printing them.

**Comment by hsbadr** [comment] 2020-12-17 01:03
@bgoodri @rok-cesnovar Actually, I've a workaround that fixes #741 without #762:

1. Don't expose the console API (`console.log`, `console.warn`, `console.error`) and don't use the deprecated `typed_arrays` argument when calling `V8::v8()`:
```
  stanc_ctx <- V8::v8(console = FALSE)
  stanc_ctx$source("https://github.com/stan-dev/stanc3/releases/download/nightly/stanc.js")
  stopifnot(stanc_ctx$validate("stanc"))
```
2. Preprocess the code to add a new line after `{` and before `}` and preferably trim the hidden whitespaces (ignore this for now as it isn't required for your simple example, but we can update the following function later. it'd be easier to use packages like `stringr` and `styler`, instead of `base R` functions, if it's ok to add dependencies):
```
stanc_preprocess <- function(model_code) {
    model_code <- gsub('\\{', '\\{\n', gsub('\\}', '\n\\}', model_code))

    # Add more preprocessing steps...

    return(model_code)
}
```
Let's test it for your simple code; this doesn't work:
`stanc_ctx$call("stanc", "comment", "data { int N; # this is an integer }")`
> $errors
> [1] "0"
> [2] "\nSyntax error in 'string', line 1, column 7 to column 13, parsing error:\n\nOnly top-level variable declarations allowed in data and parameters blocks.\n\n\n"
> 

but this works:
`stanc_ctx$call("stanc", "comment", stanc_preprocess("data { int N; # this is an integer }"))`
> $result
> [1] "\n// Code generated by stanc d01ecd3f\n#include <stan/model/model_header.hpp>\nnamespace comment_namespace {\n\n\ninline void validate_positive_index(const char* var_name, const char* expr,\n                                    int val) {\n  if (val < 1) {\n    std::stringstream msg;\n    msg << \"Found dimension size less than one in simplex declaration\"\n        << \"; variable=\" << var_name << \"; dimension size expression=\" << expr\n        << \"; expression value=\" << val;\n    std::string msg_str(msg.str());\n    throw std::invalid_argument(msg_str.c_str());\n  }\n}\n\ninline void validate_unit_vector_index(const char* var_name, const char* expr,\n                                       int val) {\n  if (val <= 1) {\n    std::stringstream msg;\n    if (val == 1) {\n      msg << \"Found dimension size one in unit vector declaration.\"\n          << \" One-dimensional unit vector is discrete\"\n          << \" but the target distribution must be continuous.\"\n          << \" variable=\" << var_name << \"; dimension size expression=\" << expr;\n    } else {\n      msg << \"Found dimension size less than one in unit vector declaration\"\n          << \"; variable=\" << var_name << \"; dimension size expression=\" << expr\n          << \"; expression value=\" << val;\n    }\n    std::string msg_str(msg.str());\n    throw std::invalid_argument(msg_str.c_str());\n  }\n}\n\n\nusing std::istream;\nusing std::string;\nusing std::stringstream;\nusing std::vector;\nusing std::pow;\nusing stan::io::dump;\nusing stan::math::lgamma;\nusing stan::model::model_base_crtp;\nusing stan::model::rvalue;\nusing stan::model::cons_list;\nusing stan::model::index_uni;\nusing stan::model::index_max;\nusing stan::model::index_min;\nusing stan::model::index_min_max;\nusing stan::model::index_multi;\nusing stan::model::index_omni;\nusing stan::model::nil_index_list;\nusing namespace stan::math;\nusing stan::math::pow; \n\nstatic int current_statement__ = 0;\nstatic const std::vector<string> locations_array__ = {\" (found before start of program)\",\n                                                      \" (in 'string', line 2, column 1 to column 7)\"};\n\n\n\nclass comment final : public model_base_crtp<comment> {\n\n private:\n  int N;\n \n public:\n  ~comment() { }\n  \n  inline std::string model_name() const final { return \"comment\"; }\n\n  inline std::vector<std::string> model_compile_info() const noexcept {\n    return std::vector<std::string>{\"stanc_version = stanc3 d01ecd3f\", \"stancflags = \"};\n  }\n  \n  \n  comment(stan::io::var_context& context__, unsigned int random_seed__ = 0,\n          std::ostream* pstream__ = nullptr) : model_base_crtp(0) {\n    using local_scalar_t__ = double ;\n    boost::ecuyer1988 base_rng__ = \n        stan::services::util::create_rng(random_seed__, 0);\n    (void) base_rng__;  // suppress unused var warning\n    static const char* function__ = \"comment_namespace::comment\";\n    (void) function__;  // suppress unused var warning\n    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());\n    (void) DUMMY_VAR__;  // suppress unused var warning\n    \n    try {\n      int pos__;\n      pos__ = std::numeric_limits<int>::min();\n      \n      pos__ = 1;\n      current_statement__ = 1;\n      context__.validate_dims(\"data initialization\",\"N\",\"int\",\n          context__.to_vec());\n      N = std::numeric_limits<int>::min();\n      \n      current_statement__ = 1;\n      N = context__.vals_i(\"N\")[(1 - 1)];\n    } catch (const std::exception& e) {\n      stan::lang::rethrow_located(e, locations_array__[current_statement__]);\n      // Next line prevents compiler griping about no return\n      throw std::runtime_error(\"*** IF YOU SEE THIS, PLEASE REPORT A BUG ***\"); \n    }\n    num_params_r__ = 0U;\n    \n    try {\n      \n    } catch (const std::exception& e) {\n      stan::lang::rethrow_located(e, locations_array__[current_statement__]);\n      // Next line prevents compiler griping about no return\n      throw std::runtime_error(\"*** IF YOU SEE THIS, PLEASE REPORT A BUG ***\"); \n    }\n  }\n  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>\n  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,\n                                                 VecI& params_i__,\n                                                 std::ostream* pstream__ = nullptr) const {\n    using T__ = stan::scalar_type_t<VecR>;\n    using local_scalar_t__ = T__;\n    T__ lp__(0.0);\n    stan::math::accumulator<T__> lp_accum__;\n    static const char* function__ = \"comment_namespace::log_prob\";\n(void) function__;  // suppress unused var warning\n\n    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);\n    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());\n    (void) DUMMY_VAR__;  // suppress unused var warning\n\n    \n    try {\n      \n    } catch (const std::exception& e) {\n      stan::lang::rethrow_located(e, locations_array__[current_statement__]);\n      // Next line prevents compiler griping about no return\n      throw std::runtime_error(\"*** IF YOU SEE THIS, PLEASE REPORT A BUG ***\"); \n    }\n    lp_accum__.add(lp__);\n    return lp_accum__.sum();\n    } // log_prob_impl() \n    \n  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>\n  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,\n                               VecI& params_i__, VecVar& vars__,\n                               const bool emit_transformed_parameters__ = true,\n                               const bool emit_generated_quantities__ = true,\n                               std::ostream* pstream__ = nullptr) const {\n    using local_scalar_t__ = double;\n    vars__.resize(0);\n    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);\n    static const char* function__ = \"comment_namespace::write_array\";\n(void) function__;  // suppress unused var warning\n\n    (void) function__;  // suppress unused var warning\n\n    double lp__ = 0.0;\n    (void) lp__;  // dummy to suppress unused var warning\n    stan::math::accumulator<double> lp_accum__;\n    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());\n    (void) DUMMY_VAR__;  // suppress unused var warning\n\n    \n    try {\n      if (logical_negation((primitive_value(emit_transformed_parameters__) ||\n            primitive_value(emit_generated_quantities__)))) {\n        return ;\n      } \n      if (logical_negation(emit_generated_quantities__)) {\n        return ;\n      } \n    } catch (const std::exception& e) {\n      stan::lang::rethrow_located(e, locations_array__[current_statement__]);\n      // Next line prevents compiler griping about no return\n      throw std::runtime_error(\"*** IF YOU SEE THIS, PLEASE REPORT A BUG ***\"); \n    }\n    } // write_array_impl() \n    \n  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>\n  inline void transform_inits_impl(const stan::io::var_context& context__,\n                                   VecI& params_i__, VecVar& vars__,\n                                   std::ostream* pstream__ = nullptr) const {\n    using local_scalar_t__ = double;\n    vars__.clear();\n    vars__.reserve(num_params_r__);\n    \n    try {\n      int pos__;\n      pos__ = std::numeric_limits<int>::min();\n      \n      pos__ = 1;\n    } catch (const std::exception& e) {\n      stan::lang::rethrow_located(e, locations_array__[current_statement__]);\n      // Next line prevents compiler griping about no return\n      throw std::runtime_error(\"*** IF YOU SEE THIS, PLEASE REPORT A BUG ***\"); \n    }\n    } // transform_inits_impl() \n    \n  inline void get_param_names(std::vector<std::string>& names__) const {\n    \n    names__.clear();\n    \n    } // get_param_names() \n    \n  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {\n    dimss__.clear();\n    \n    } // get_dims() \n    \n  inline void constrained_param_names(\n                                      std::vector<std::string>& param_names__,\n                                      bool emit_transformed_parameters__ = true,\n                                      bool emit_generated_quantities__ = true) const\n    final {\n    \n    \n    if (emit_transformed_parameters__) {\n      \n    }\n    \n    if (emit_generated_quantities__) {\n      \n    }\n    \n    } // constrained_param_names() \n    \n  inline void unconstrained_param_names(\n                                        std::vector<std::string>& param_names__,\n                                        bool emit_transformed_parameters__ = true,\n                                        bool emit_generated_quantities__ = true) const\n    final {\n    \n    \n    if (emit_transformed_parameters__) {\n      \n    }\n    \n    if (emit_generated_quantities__) {\n      \n    }\n    \n    } // unconstrained_param_names() \n    \n  inline std::string get_constrained_sizedtypes() const {\n    stringstream s__;\n    s__ << \"[]\";\n    return s__.str();\n    } // get_constrained_sizedtypes() \n    \n  inline std::string get_unconstrained_sizedtypes() const {\n    stringstream s__;\n    s__ << \"[]\";\n    return s__.str();\n    } // get_unconstrained_sizedtypes() \n    \n  \n    // Begin method overload boilerplate\n    template <typename RNG>\n    inline void write_array(RNG& base_rng,\n                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,\n                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,\n                            const bool emit_transformed_parameters = true,\n                            const bool emit_generated_quantities = true,\n                            std::ostream* pstream = nullptr) const {\n      std::vector<double> vars_vec(vars.size());\n      std::vector<int> params_i;\n      write_array_impl(base_rng, params_r, params_i, vars_vec,\n          emit_transformed_parameters, emit_generated_quantities, pstream);\n      vars.resize(vars_vec.size());\n      for (int i = 0; i < vars.size(); ++i) {\n        vars.coeffRef(i) = vars_vec[i];\n      }\n    }\n\n    template <typename RNG>\n    inline void write_array(RNG& base_rng, std::vector<double>& params_r,\n                            std::vector<int>& params_i,\n                            std::vector<double>& vars,\n                            bool emit_transformed_parameters = true,\n                            bool emit_generated_quantities = true,\n                            std::ostream* pstream = nullptr) const {\n      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);\n    }\n\n    template <bool propto__, bool jacobian__, typename T_>\n    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,\n                       std::ostream* pstream = nullptr) const {\n      Eigen::Matrix<int, -1, 1> params_i;\n      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);\n    }\n\n    template <bool propto__, bool jacobian__, typename T__>\n    inline T__ log_prob(std::vector<T__>& params_r,\n                        std::vector<int>& params_i,\n                        std::ostream* pstream = nullptr) const {\n      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);\n    }\n  \n\n    inline void transform_inits(const stan::io::var_context& context,\n                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,\n                         std::ostream* pstream = nullptr) const final {\n      std::vector<double> params_r_vec(params_r.size());\n      std::vector<int> params_i;\n      transform_inits_impl(context, params_i, params_r_vec, pstream);\n      params_r.resize(params_r_vec.size());\n      for (int i = 0; i < params_r.size(); ++i) {\n        params_r.coeffRef(i) = params_r_vec[i];\n      }\n    }\n    inline void transform_inits(const stan::io::var_context& context,\n                                std::vector<int>& params_i,\n                                std::vector<double>& vars,\n                                std::ostream* pstream = nullptr) const final {\n      transform_inits_impl(context, params_i, vars, pstream);\n    }        \n\n};\n}\nusing stan_model = comment_namespace::comment;\n\n#ifndef USING_R\n\n// Boilerplate\nstan::model::model_base& new_model(\n        stan::io::var_context& data_context,\n        unsigned int seed,\n        std::ostream* msg_stream) {\n  stan_model* m = new stan_model(data_context, seed, msg_stream);\n  return *m;\n}\n\n#endif\n\n\n"
> 
> $warnings
> list()
>

**Comment by rok-cesnovar** [comment] 2020-12-17 08:24
> Don't expose the console API (console.log, console.warn, console.error)

Not exposing is not really an option, unfortunately. Only maybe to test other stuff while we wait for #762. We want these warnings, just not printed but returned. 

There is the possibility of rerouting it to a global variable, like I did here: https://github.com/rok-cesnovar/stanc3js-demo/blob/4429a2df3d4be4cdfe3eb7939f21c5cf714eff6f/pedantic.html#L6 but that is just masking the issue. And we also want to limit the amount of JS we run.

> Preprocess the code to add a new line after { and before }

Yeah, this might help this example to compile. However, I am not sure we want it to as this would deviate from the binary stanc3.
If I place 
```
data { int N; # this is an integer }
```
in a .stan file and compile I get:
```
--- Translating Stan model to C++ code ---
bin/stanc  --o=examples/test/test.hpp examples/test/test.stan

Warning: deprecated language construct used in 'examples/test/test.stan', line 1, column 14:
   -------------------------------------------------
     1:  data { int N; # this is an integer }
                       ^
   -------------------------------------------------

Comments beginning with # are deprecated. Please use // in place of # for line comments.


Syntax error in 'examples/test/test.stan', line 1, column 7 to column 13, parsing error:
   -------------------------------------------------
     1:  data { int N; # this is an integer }
                      ^
   -------------------------------------------------

Only top-level variable declarations allowed in data and parameters blocks.
```

**Comment by hsbadr** [comment] 2020-12-17 15:53
> Yeah, this might help this example to compile. However, I am not sure we want it to, as this would deviate from the binary stanc3.

I see. I wanted to make the `#` comments at the end of each line not inside `{}`, but I understand why you'd like to support a deprecated syntax and return the warnings.

BTW. While I was able to generate and compile the models using `rstan` with `stanc3`, stan-dev/math/pull/2190 causes runtime errors (I guess it needs an update in `rstan` to evaluate the expressions?). Other than that, everything works fine with `rstan` and the current development versions of `stan` and `math`. I've been using Stan `2.25.0` with `rstan` since release.

**Comment by rok-cesnovar** [comment] 2020-12-17 16:40
> return the warnings

We would also like to support warnings because of flags like "warn-pedantic" that print out various other warnings about your model.

> While I was able to generate and compile the models using rstan with stanc3, stan-dev/math/pull/2190 causes runtime errors (I guess it needs an update in rstan to evaluate the expressions?).

So that is with the latest stan math and latest stanc3 and you are getting runtime errors? There might be stuff missing that are on the Stan layer, where we also had to change a few things to support Eigen expressions.

If possible, can you give a reproducible example? Thanks!

**Comment by hsbadr** [comment] 2020-12-17 16:49
> So that is with the latest stan math and latest stanc3 and you are getting runtime errors?

Yes. The C++ code compiles but it seems that the `rstan_fit` needs to be updated to support Eigen expressions. I'm rebasing on `rstan/try_2.25` and will give you a reproducible example and logs ASAP.

**Comment by rok-cesnovar** [comment] 2020-12-17 16:58
> I'm rebasing on rstan/try_2.25 and will give you a reproducible example and logs ASAP.

Thanks!

**Comment by hsbadr** [comment] 2020-12-18 16:15
@rok-cesnovar FYI. A couple things that are already missing and need to be implemented/overridden in `rstan`: `model_compile_info()` and `stan::io::validate_dims`. I'll revert the related commits in `math` and will create an example for you.

**Comment by hsbadr** [comment] 2020-12-18 19:49
@rok-cesnovar I've fixed the runtime errors. They're mainly from the `R` functions in `rstan`. For example, [`rstan:::parse_data()`](https://github.com/stan-dev/rstan/blob/84274158a8bdcb7227ab7bd021355188d1b325b4/rstan/rstan/R/misc.R#L1597-L1614)  expects that the `private:` and `public:` classes start from the beginning of the line with no spaces:
```
  private <- grep("^private:$", cppcode) + 1L
  public <- grep("^public:$", cppcode) - 1L 
```
but, the C++ code generated by `stanc3` has a leading space where the following would work:
```
  private <- grep("^private:$| private:$", cppcode) + 1L
  public <- grep("^public:$| public:$", cppcode) - 1L
```
Also, the `in_data` objects are missed in the parser code:
```
  in_data <- grep("context__.vals_", cppcode, fixed = TRUE, value = TRUE)
  in_data <- gsub('^.*\\("(.*)\"\\).*;$', "\\1", in_data)
```  
Fixing the data parsing errors from `rstan:::parse_data()` resolves the runtime issues for my mode, but there may be other similar updates needed to correctly parse the C++ code for every model.

@bgoodri I'd like to submit a PR to support Stan 2.25.0, but I'm not sure if this should target `rstan/develop` or `rstan/try_2.25`, and the `stan` submodule needs to be updated (either by updating `rstan` code to override `model_compile_info()` and support `stan::io::validate_dims` or by creating a new branch in `stan` for `rstan_2.25` ). What do you think?

**Comment by bgoodri** [comment] 2020-12-18 20:00
I would say branch off of the try_2.25 rstan branch. I'll create branches
for StanHeaders that correspond to 2.25.

**Comment by hsbadr** [comment] 2020-12-18 20:10
> I would say branch off of the try_2.25 rstan branch. I'll create branches for StanHeaders that correspond to 2.25.

Thanks! Both `rstan` and `StanHeaders` are in the same repo, as you know. Both have been updated. The problem is in the `stan` submodule where we need to apply https://github.com/hsbadr/stan/commit/5a5e1389425a9acfc18e8faa0e5d79510ebe4635 or implement the required changes in `rstan`. Can you tell me where to start to override `model_compile_info()` and support `stan::io::validate_dims` in `rstan`? If we do so, we can directly track the `develop` branches of `stan` and `math`.

If I'll submit a PR now, I'll be tracking my `stan` fork; otherwise, compilation will fail.

**Comment by bgoodri** [comment] 2020-12-18 20:33
I just branched StanHeaders_2.25 branches off of master for Stan and Math.
There are going to be some other patches that we have to apply to in order
to be backward compatible with Stuff on CRAN. If we need some post-2.25
stuff to make rstan work, we can backport those PRs. I would guess
stan::io::validate_dims doesn't need to be specialized by rstan (although
we do need something that works for 2.21 as well as 2.25). What does
model_compile_info() do and where?

**Comment by rok-cesnovar** [comment] 2020-12-18 20:35
`model_compile_info()` in the model returns a vector of the stanc3 version and flags used when compiling. 

```
inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 2.25.0", "stancflags = --allow-undefined"};
}
```

**Comment by hsbadr** [comment] 2020-12-18 20:37
> What does model_compile_info() do and where?

It retrieves the info about the compiler version and flags used, introduced in https://github.com/stan-dev/stan/pull/2932.

**Comment by bgoodri** [comment] 2020-12-18 20:43
OK. That sounds like it would go into src/Module.cpp of rstan.

**Comment by hsbadr** [comment] 2020-12-18 20:44
@rok-cesnovar Check https://github.com/hsbadr/EpiNow2/commit/b320b59595073b632d61e7337909e24e96ab58ba; it's an example of the differences in C++ code generated by the old and new `stanc`. One thing I don't like about the code generated by `stanc3` is the following stuff:
```
using stan::math::pow;
static int current_statement__ = 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'string', line 637, column 2 to column 55)",
                                                      " (in 'string', line 638, column 2 to column 39)",
                                                      ...
```
The `'string'` here and line numbers should be tracing the correct files and includes (`#include ...`) as before:
```
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_estimate_infections");
    reader.add_event(1, 1, "include", "functions/pmfs.stan");
    reader.add_event(1, 0, "start", "functions/pmfs.stan");
    ...
```
Since `rstan` generates the code from `tmp` files, the raw generated code isn't useful either b/c it replaces `'string'` with `tmp` paths.

**Comment by hsbadr** [comment] 2020-12-18 20:46
> OK. That sounds like it would go into src/Module.cpp of rstan.

Ok. I'll take a look.

Here's my fork if you'd like to cherry pick: https://github.com/hsbadr/rstan

**Comment by hsbadr** [comment] 2020-12-18 21:06
> There are going to be some other patches that we have to apply to in order to be backward compatible with Stuff on CRAN. If we need some post-2.25 stuff to make rstan work, we can backport those PRs.

@bgoodri Sounds good. I'll submit patches in separate PRs to distinguish between backward compatible patches (targeting  `rstan/develop`) and the post-2.5 patches (targeting `rstan/try_2.5`). I think all patches are backward compatible if we keep the old `rstan::scanc` code and check the version of `stan`.

**Closed** 2020-12-27 16:32 UTC
