### ISSUE TITLE
Improve error messages for data-only argument enforcement

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#255] opened 2019-08-13 14:19 UTC
Currently, error messages are confusing for cases where type checking fails because of a mismatching data-only restriction. This can be made much clearer by printing `data` as a part of the types of the specified arguments if the compiler can derive that an argument is of data-only autodiff level.

**Comment by seantalts** [comment] 2019-08-13 14:24
What is "argument reinforcement?"

**Comment by VMatthijs** [comment] 2019-08-13 15:06
> What is "argument reinforcement?"

Thanks for catching the typo

**Comment by seantalts** [comment] 2019-08-13 15:07
Oh, sorry, I thought it was a PL word, haha.

**Comment by rok-cesnovar** [comment] 2020-06-17 18:11
Duplicate of #9

**Closed by rok-cesnovar** 2020-06-17 18:11 UTC
Labels: feature, good first issue
