### ISSUE TITLE
Add Static Matrix Type For Compiler Optim

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stanc3#668] opened 2020-08-08 01:10 UTC
## Summary

This is the tech spec for when the compiler can optimize an `Eigen::Matrix<var, -1, -1>` (dynamic matrix) into a `var_value<Eigen::Matrix<double, -1, -1>>` (static matrix)

## Conditions

1. The matrix/vector never has subslices of it assigned to ex:

```stan
matrix[N, M] A = // fill A;
vector[N] B = // fill B;
A[N, 1] = B; // Makes A dynamic
```

(optional) entire assignment could be fine

```stan
matrix[N, M] A = // fill A;
A += A * A'; // still static!
```

2. There is a signature available that accepts a static matrix
- This is currently WIP, but the first one will probably be `multiply()`

3. The matrix is operated on along with a dynamic matrix.

```stan
matrix[N, M] A = // fill A;
vector[N] B;
matrix[N, M] C;
for (i in 1:N) {
  B[i] = i; // fill dynamically
}
C = A * B; // C will be dynamic
```

I have an example program here has these as examples

```stan
data {
  int N;
  int M;
  vector[N] y;
}

parameters {
  matrix[N, M] x_mat_p_static;
  vector[N] x_vec_p_static;
}

transformed parameters {
  // static matrices
  matrix[N, M] x_mat_tp_static;
  vector[N] x_vec_tp_static;
  // dynamic matrix
  matrix[N, M] x_mat_tp_dynamic;
  // static matrix
  vector[10] mat_vec_mul_static = x_mat_p_static[1:10, 1:10] * x_vec_tp_static[1:10];
  // dynamic matrix
  vector[10] mat_vec_mul_dynamic;
  for (i in 1:(N * M)) {
    x_mat_tp_dynamic[i] = x_mat_p_static[i];
  }
  // dynamic matrix
  mat_vec_mul_dynamic = x_mat_tp_dynamic[1:10, 1:10] * x_vec_tp_static[1:10];
}
```

For the C++ I think the easiest thing to do would be to have a type trait called `static_matrix_converter_t` that takes in an eigen matrix and a true/false value like 

```cpp
/**
 * Type trait to make eigen<var> to var<eigen> types
 * @tparam T A type inheriting from `EigenBase`
 * @tparam static_mat if true, `type` is `var<eigen>`, else `type` is `eigen<var>`
 */
template <typename T, bool static_mat, typename = void>
struct static_matrix_converter;

/**
 * Overload, when `static_mat` is true and value type of `T` is `var`, then
 * `type` is a var<eigen>`
 */
template <typename T>
struct static_matrix_converter<T, true, require_var_t<value_type_t<T>>> {
  using type = var_value<Eigen::Matrix<double, T::RowsAtCompileTime, T::ColsAtCompileTime>;
};

/**
 * Overload, when `static_mat` is false and value type of `T` is `var`, then
 * `type` is a `eigen<var>`
 */
template <typename T>
struct static_matrix_converter<T, false, require_var_t<value_type_t<T>>> {
  using type = T;
};

/**
 * Overload, when `static_mat` is false and value type of `T` is `arithmetic`, then
 * `type` is a `eigen<arithmetic>`
 */
template <typename T, bool static_mat>
struct static_matrix_converter<T, static_mat, require_arithmetic_t<value_type_t<T>>> {
  using type = T;
};

// Helper alias
template <typename T, bool static_mat = false>
using static_matrix_converter_t = static_matrix_converter<T, static_mat>::value;
```

So each instance will look like
```
static_matrix_converter_t<Eigen::Matrix<var, -1, -1>, true>  ==
// return type
var_value<Eigen::Matrix<double, -1, -1>>


static_matrix_converter_t<Eigen::Matrix<var, -1, -1>, false> ==
// return type
Eigen::Matrix<var, -1, -1>

static_matrix_converter_t<Eigen::Matrix<double, -1, -1>, true> ==
// same for true/false
Eigen::Matrix<var, -1, -1>

```

and the compiler sets the `true/false` value for each matrix if it checks all the boxes above

We can use the above for things like `log_prob()` that work for `var` and `double`. Using the above stan program as an example `log_prob` will be

```cpp
  template <bool propto__, bool jacobian__, typename T__>
  inline T__ log_prob(std::vector<T__> &params_r__,
                      std::vector<int> &params_i__,
                      std::ostream *pstream__ = nullptr) const {
    using local_scalar_t__ = T__;
    // Little helpers for readability
    using eigen_mat = Eigen::Matrix<local_scalar_t__, -1, -1>;
    using eigen_vec = Eigen::Matrix<local_scalar_t__, -1, 1>;
    using eigen_row_vec = Eigen::Matrix<local_scalar_t__, 1, -1>;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char *function__ = "tester_model_namespace::log_prob";
    (void)function__; // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void)DUMMY_VAR__; // suppress unused var warning

    try {
      // var_value<Eigen::Matrix<double, -1, -1>>
      static_matrix_converter_t<eigen_mat, true> x_mat_p_static;
      x_mat_p_static = static_matrix_converter_t<eigen_mat, true>(N, M);
      stan::math::fill(x_mat_p_static, DUMMY_VAR__);

      current_statement__ = 1;
      /**
       * New function
       */
      x_mat_p_static = in__.static_matrix(N, M);
      // var_value<Eigen::Matrix<double, -1, 1>>
      static_matrix_converter_t<eigen_vec, true> x_vec_p_static;
      x_vec_p_static = static_matrix_converter_t<eigen_vec, true>(N);
      stan::math::fill(x_vec_p_static, DUMMY_VAR__);

      current_statement__ = 2;
      /**
       * New function
       */
      x_vec_p_static = in__.static_vector(N);
      // var_value<Eigen::Matrix<double, -1, -1>>
      static_matrix_converter_t<eigen_mat, true> x_mat_tp_static;
      x_mat_tp_static = static_matrix_converter_t<eigen_mat, true>(N, M);
      stan::math::fill(x_mat_tp_static, DUMMY_VAR__);

      // var_value<Eigen::Matrix<double, -1, 1>>
      static_matrix_converter_t<eigen_vec, true> x_vec_tp_static;
      x_vec_tp_static = static_matrix_converter_t<eigen_vec, true>(N);
      stan::math::fill(x_vec_tp_static, DUMMY_VAR__);
      // Eigen::Matrix<var, -1, -1>
      static_matrix_converter_t<eigen_mat, false> x_mat_tp_dynamic;
      x_mat_tp_dynamic = static_matrix_converter_t<eigen_mat, false>(N, M);
      stan::math::fill(x_mat_tp_dynamic, DUMMY_VAR__);
      // var_value<Eigen::Matrix<double, -1, 1>>
      static_matrix_converter_t<eigen_vec, true> mat_vec_mul_static;
      mat_vec_mul_static = static_matrix_converter_t<eigen_vec, true>(10);
      stan::math::fill(mat_vec_mul_static, DUMMY_VAR__);

      current_statement__ = 6;
      assign(mat_vec_mul_static, nil_index_list(),
             multiply(rvalue(x_mat_p_static,
                             cons_list(index_min_max(1, 10),
                                       cons_list(index_min_max(1, 10),
                                                 nil_index_list())),
                             "x_mat_p_static"),
                      rvalue(x_vec_tp_static,
                             cons_list(index_min_max(1, 10), nil_index_list()),
                             "x_vec_tp_static")),
             "assigning variable mat_vec_mul_static");
      // Eigen::Matrix<var, -1, 1>
      static_matrix_converter_t<eigen_vec, false> mat_vec_mul_dynamic;
      mat_vec_mul_dynamic = static_matrix_converter_t<eigen_vec, false>(10);
      stan::math::fill(mat_vec_mul_dynamic, DUMMY_VAR__);

      current_statement__ = 10;
      for (int i = 1; i <= (N * M); ++i) {
        current_statement__ = 8;
        assign(x_mat_tp_dynamic, cons_list(index_uni(i), nil_index_list()),
               rvalue(x_mat_p_static, cons_list(index_uni(i), nil_index_list()),
                      "x_mat_p_static"),
               "assigning variable x_mat_tp_dynamic");
      }
      current_statement__ = 11;
      assign(mat_vec_mul_dynamic, nil_index_list(),
             multiply(rvalue(x_mat_tp_dynamic,
                             cons_list(index_min_max(1, 10),
                                       cons_list(index_min_max(1, 10),
                                                 nil_index_list())),
                             "x_mat_tp_dynamic"),
                      rvalue(x_vec_tp_static,
                             cons_list(index_min_max(1, 10), nil_index_list()),
                             "x_vec_tp_static")),
             "assigning variable mat_vec_mul_dynamic");
    } catch (const std::exception &e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  } // log_prob()
```

**Comment by rok-cesnovar** [comment] 2020-08-08 13:55
Does assigment of a static matrix to a dynamic matrix work? 

So a result of a multiply of 2 static matrices will now be a static matrix that we then need to assign to a dynamic one to continue. Right?

**Comment by rok-cesnovar** [comment] 2020-08-08 18:23
Otherwise, I think the best place to start would be to make a test stanc3 version (not on master obviously) that would generate static matrix C++ for any Stan matrix, vector, or row_vector for variables with names with a specific suffix (_static for example). That would be really easy to implement and with that we can double-check that everything on the C++ side works, the results match, etc. We could also run model performance tests with that. 

Then once that is confirmed to work we can then swap the suffix logic with the actual logic that will check whether a matrix is static or not. That would make it much simpler to track down any potential bugs compared to a version where we try to make everything at once. What do you think?

**Comment by SteveBronder** [comment] 2020-08-10 16:41
> Does assigment of a static matrix to a dynamic matrix work?

So the rules we want are that for `multiply(static, dynamic)` the result will be a dynamic matrix. imo I think that's going to be less expensive in the long run since the cost of a `static->dynamic` copy is expensive. Essentially if a function takes in both a static and dynamic matrix the result will be dynamic. If they are both static then the output will continue to be static

**Comment by wds15** [comment] 2020-08-10 18:00
And what if I multiply static with dynamic, but never touch the result any more?

**Comment by rok-cesnovar** [comment] 2020-08-10 18:08
@SteveBronder That seems reasonable. 

How about 

```
a = multiply(static, static)
b = foo(a) 
```

where foo does not yet support static? Do we have a `to_dynamic()` or something? That was essentially my question in the first place but I worded it badly.

> And what if I multiply static with dynamic, but never touch the result any more?

Not sure, but I am guessing that stays dynamic because the dynamic one has some matrix elements with different expressions to autodiff for some elements and we want to make sure that those are evaluate properly?

**Comment by SteveBronder** [comment] 2020-08-10 22:13
> How about

```
a = multiply(static, static)
b = foo(a) 
```

> where foo does not yet support static? Do we have a to_dynamic() or something? That was essentially my question in the first place but I worded it badly.

So we could do two things here

1. We can have a `to_dynamic()` function so the compiler would generate

```
a = multiply(static, static)
b = foo(to_dynamic(a)) 
```

Or 

2. Look at `a` and if it's used in a function without a static matrix impl then have `a` be a dynamic matrix. We have implicit converters from `var_value<Eigen>` to `Eigen<var>`. so if `multiply(static, static)` returns a `static` we would convert it to a dynamic matrix implicitly i.e. the following is value

```
var_value<Eigen::Matrix<double, -1, -1>> a = // fill a;
var_value<Eigen::Matrix<double, -1, -1>> b = // fill b;
// var_value<Matrix> result of multiply(a, b) is implicitly convertible to Matrix<var>
Eigen::Matrix<var, -1, -1> c = multiply(a, b); 
Eigen::Matrix<var, -1, -1> d = foo(c);
```

**Comment by SteveBronder** [comment] 2020-08-10 22:14
Does that answer your Q?

**Comment by rok-cesnovar** [comment] 2020-08-11 05:55
Yes. Thanks. Have to think about it a bit more. 1 seems easier to implement at first glance.

**Comment by rok-cesnovar** [comment] 2020-08-28 09:14
Just a note so it does not get forgotten. As @t4c1 notes in https://github.com/stan-dev/math/issues/2045 we will require:

`using var_value_vector = std::conditional_t<is_var<Argument>::value, var_value<Eigen::VectorXd>>, Eigen::VectorXd>;` (and same for matrix and row vector) and than use this when it determines var_value should be used

This should be generated by stanc3 if var_value is used anywhere.

**Comment by rok-cesnovar** [comment] 2020-12-02 20:06
Toy model time:

```
data {
    int N;
    vector[N] d_vector;
}

parameters {
    vector[N] p1_vector;
    vector[N] p2_vector;
}
model {
    target += normal_lpdf(d_vector| p1_vector, p2_vector);
}
```
relevant parts currently compile to:

```cpp
Eigen::Matrix<local_scalar_t__, -1, 1> p1_vector;
p1_vector = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
stan::math::fill(p1_vector, DUMMY_VAR__);
      
current_statement__ = 1;
p1_vector = in__.vector(N);
Eigen::Matrix<local_scalar_t__, -1, 1> p2_vector;
p2_vector = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
stan::math::fill(p2_vector, DUMMY_VAR__);
      
current_statement__ = 2;
p2_vector = in__.vector(N);
{
        current_statement__ = 3;
        lp_accum__.add(normal_lpdf<false>(d_vector, p1_vector, p2_vector));
}
```

Does this look right? The two commented-out lines do not compile currently.
```cpp
using var_value_vector = std::conditional_t<stan::is_var<local_scalar_t__>::value, stan::math::var_value<Eigen::VectorXd>, Eigen::VectorXd>;
var_value_vector p1_vector_varmat;
p1_vector_varmat = Eigen::Matrix<double, -1, 1>(N);
stan::math::initialize_fill(p1_vector_varmat, DUMMY_VAR__);

current_statement__ = 1;
// p1_vector_varmat = in__.vector(N);
var_value_vector p2_vector_varmat;
p2_vector_varmat = Eigen::Matrix<double, -1, 1>(N);
stan::math::initialize_fill(p2_vector_varmat, DUMMY_VAR__);

current_statement__ = 2;
// p2_vector = in__.vector(N);
{
  current_statement__ = 3;
  lp_accum__.add(normal_lpdf<false>(d_vector, p1_vector_varmat, p2_vector_varmat));
}
```

**Comment by SteveBronder** [comment] 2020-12-02 20:32
That looks correct to me, is it compiling?

**Comment by rok-cesnovar** [comment] 2020-12-02 20:33
It is.

**Comment by SteveBronder** [comment] 2020-12-02 20:36
Nice!

**Closed** 2024-01-31 19:25 UTC
Labels: big-exciting-project, optimization
